spring:
  datasource:
    url: jdbc:h2:file:~/poc-db;DATABASE_TO_UPPER=false;NON_KEYWORDS=USER,NAME;
    driver-class-name: org.h2.Driver
    username: sa
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

jwt:
  secret: 227c8378-be62-4b7f-9a69-c8967e40b6c9
  expiration: 600000

springdoc:
  show-login-endpoint: true
  swagger-ui:
    default-models-expand-depth: -1